server:
  port: 18080

spring:
  application:
    name: eureka-server

eureka:
  instance:
    hostname: localhost
  #    ip-address: 192.168.3.150
  #    prefer-ip-address: true
  #    non-secure-port: 80
  #    secure-port: 443
  #    non-secure-port-enabled: true
  #    secure-port-enabled: true
  # 自我保护机制:Eureka Server在运行期间，会统计心跳失败的比例在15分钟之内是否低于85%，
  # 如果出现低于的情况（在单机调试的时候很容易满足，实际在生产环境上通常是由于网络不稳定导致），Eureka Server会将当前的实例注册信息保护起来(该服务一直存在，且为UP状态)，
  # 同时提示这个警告:EMERGENCY! EUREKA MAY BE INCORRECTLY CLAIMING INSTANCES ARE UP WHEN THEY'RE NOT. RENEWALS ARE LESSER THAN THRESHOLD AND HENCE THE INSTANCES ARE NOT BEING EXPIRED JUST TO BE SAFE.
  server:
    enable-self-preservation: true # 关闭自我保护
    eviction-interval-timer-in-ms: 20000 # 清理间隔时间

  client:
    register-with-eureka: false
    fetch-registry: false
    service-url:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/